services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "${MINECRAFT_PORT}:25565"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      MEMORY: 2G
      VERSION: "1.21.11"
    volumes:
      - ${DATA_DIR}/minecraft:/data
    networks:
      - proxy

